### ISSUE TITLE
New Tutorial: Quiz Game

### ISSUE THREAD

**Issue by Sreehari521** [Educational-Websites/ScratchTutorials#2]
**My Tutorial is about a quiz game**
My tutorial is about a quiz game. The project level is medium type and the link to the project is https://scratch.mit.edu/projects/525717354/. Also, my scratch profile is https://scratch.mit.edu/users/ASTRONAUT_521/.

It will be appreciated if my project will be added to the website.

Thanks
Sreehari

**Comment by Genius398** [comment]
Thanks. Your request is approved. It will take 1-2 hours for it to be added. Meanwhile, just relax

**Comment by Genius398** [comment]
Done. Added in the website

Have a good day 😀🙂
