### ISSUE TITLE
New Tutorial Idea

### ISSUE THREAD

**Issue by Genius398** [Educational-Websites/ScratchTutorials#24]
### Discussed in https://github.com/Educational-Websites/ScratchTutorials/discussions/23

<div type='discussions-op-text'>

<sup>Originally posted by **Sreehari521** August  8, 2021</sup>
Y don't we create our own library and publish with npm and create tutorials on that</div>

**Comment by somePythonProgrammer** [comment]
@Sreehari521 I think that 'node.js' would be a better word to use, instead of 'npm'

**Comment by Genius398** [comment]
Did you see the whole thing

**Comment by Genius398** [comment]
Guys let's do this is the discussion page
