### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Super45coder** [Educational-Websites/ScratchTutorials#35]
I contributed to the website, but there is a big gap between by tutorial and the first one. That shouldn't be there. Also, now I don't have access to add code and it forks this whenever I try to.

**To Reproduce**
1. Go to the website.
2. Scroll down to bottom
3. See error
4. Go to github
5. Go to the scratch tutorials code
6. Go to index.html.
7. Press edit.
8. See error

**Expected behavior**
I thought that the 2 tutorials would be close together and that I could edit the document freely.

**Comment by Genius398** [comment]
This is expected behaviour. Without the <table> tag, the CSS evenly spaces the tutorial divs. no need to worry about it.

However we might start using the table and tr tags in the future

**Comment by Genius398** [comment]
Working as needed 😀🙂
